requires 'Mojolicious' => 9;
requires 'DBIx::Class';
requires 'DBIx::Class::Helper::Row::ToJSON';
requires 'Mojolicious::Plugin::NotYAMLConfig';
requires 'DBD::mysql';
requires 'Mojolicious::Plugin::OpenAPI';
requires 'Mojolicious::Plugin::SwaggerUI';
requires 'Mojolicious::Plugin::Authentication';
requires 'CryptX';
requires 'Mojo::mysql';
requires 'Mojo::mysql::Migrations';
requires 'Mojo::JWT';
